### ISSUE TITLE
[JOSS-Review] Installation + CLI Issues

### ISSUE THREAD

**Issue by Manvi-Agrawal** [souradipp76/ReadMeReady#15]
### JOSS Reviewer checklist item: Installation
**JOSS Review Issue:** https://github.com/openjournals/joss-reviews/issues/7489

### Installation Issue
After doing `pip install readme-ready` and the running CLI command `readme-ready`, I am getting the following error:
`readme-ready: The term 'readme-ready' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

**System Info:**
OS: Windows 11
Python 3.11.9
pip: 24.3.1

**Comment by souradipp76** [comment]
Hi @Manvi-Agrawal, the CLI command is `readme_ready` with an underscore to launch the CLI app.
You can also check out the code example at `examples/example.py`. You might have to change the configuration parameters based on your setup.

**Comment by Manvi-Agrawal** [comment]
My bad. OOPS! 
Now, I am getting : "ImportError: failed to find libmagic.  Check your installation". I installed python-libmagic-bin and this error got fixed.

 On entering these details in CLI, i get:  

Initializing Auto Documentation...
? Project Name?[Example: readme_ready] readme_ready
? Project Root?[Example: ./readme_ready/] ./readme_ready/
? Project URL?[Example: https://github.com/username/readme_ready] https://github.com/souradipp76/ReadMeReady
? Output Directory?[Example: ./output/readme_ready/] ./output/readme_ready/
? Documentation Mode? Readme
? List of Readme Headings?(comma separated)[Example: # Introduction,## Usage]  # Introduction,## Usage
? Which model? meta-llama/Llama-2-7b-chat-hf
? Is finetuned? No
? Device? cpu
Initialization Complete.

Processing repository...
The provided folder path does not exist.
Processing 0 files and 0 folders...
The provided folder path does not exist.
Processing complete.
Creating markdown files...
Creating vector files...
[WinError 3] The system cannot find the path specified: './readme_ready/'
Traceback (most recent call last):
  File "C:\Users\manvi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\readme_ready\index\create_vector_store.py", line 52, in process_directory
    files = os.listdir(directory_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: './readme_ready/'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\...\readme_ready\__main__.py", line 6, in <module>
    main()
  File "C:\...\readme_ready\main.py", line 190, in main
    index.index(repo_conf)
  File "C:\...\readme_ready\index\index.py", line 75, in index
    create_vector_store(
  File "C:\...\readme_ready\index\create_vector_store.py", line 100, in create_vector_store
    raw_docs = loader.load()
               ^^^^^^^^^^^^^
  File "C:\...\readme_ready\index\create_vector_store.py", line 85, in load
    return process_directory(self.file_path, self.ignore)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\readme_ready\index\create_vector_store.py", line 55, in process_directory
    raise FileNotFoundError(
FileNotFoundError: Could not read directory: ./readme_ready/.

**Comment by souradipp76** [comment]
Project Root refers to the path to the code repository you want to generate a README for. Please download any sample code repository from GitHub and use that or if you have your own repository downloaded (say `MyRepo`) you can use that as well. Set Project Root as `<path to MyRepo>` and set the other parameters accordingly. Output Directory is where the README will be generated(you can set any appropriate path). For Windows platforms, please provide the paths correctly (e.g. C:\Users\_user_\Downloads\MyRepo).

Also, I would suggest using GPU since LLMs like `meta-llama/Llama-2-7b-chat-hf` take a lot of resources (~13.5 GB) and may run slowly on CPU, even with 4bit quantization(added by default). 

Also, please upgrade the package to its latest version 1.1.3.

**Comment by souradipp76** [comment]
As for the error "ImportError: failed to find libmagic", I will add an additional step for installation in the documentation to install the `python-magic`[link](https://pypi.org/project/python-magic/) since the installation is different for Windows platform.

**Comment by Manvi-Agrawal** [comment]
@souradipp76 I don't have GPU access. Do you think T4 GPU provided by collab would work for verification?

**Comment by souradipp76** [comment]
Yes. You can use T4 GPU provided by Google Colab for verification.

**Comment by Manvi-Agrawal** [comment]
> Project Root refers to the path to the code repository you want to generate a README for. Please download any sample code repository from GitHub and use that or if you have your own repository downloaded (say MyRepo) you can use that as well. Set Project Root as <path to MyRepo> and set the other parameters accordingly. Output Directory is where the README will be generated(you can set any appropriate path). For Windows platforms, please provide the paths correctly (e.g. C:\Users\user\Downloads\MyRepo).

@souradipp76 , thanks for the explaination. Possibly consider adding these explainations in README for future devs.

- Also, could you please explain how can someone use the github url prompt efficiently. I am assuming that would allow users to generate readme for a project existing on github, is that correct?

- Also, I am still getting `FileNotFoundError: Could not read directory: ./readme_ready/.` in google collab with T4 gpu. I set the hf-token and open-ai token as random guids. and ran code in `examples/example.py`

**Comment by souradipp76** [comment]
@Manvi-Agrawal, I have added additional instructions in README as well in `examples/example.py`.
- In case there is no GitHub URL, the user can leave it blank.
- For the `FileNotFoundError`, please set the exact directory path where the repository is located. The paths need to be changed accordingly depending on which directory you are running the script from.

**Comment by souradipp76** [comment]
@Manvi-Agrawal Please see the example to run in Google Colab with GPU as mentioned [here](https://github.com/openjournals/joss-reviews/issues/7489#issuecomment-2571711162).

**Comment by Manvi-Agrawal** [comment]
Thanks @souradipp76 the shared example worked without any issues with T4 GPU. I ended up commenting `login(token=HF_TOKEN, add_to_git_credential=False)` and used fake HF token for `LLAMA2_7B_CHAT_GPTQ` model.

Closing the issue since I am able to run on GPU.
